import { reviewPaymentForm } from "@/app/actions/payment";
import { PageHeading } from "@/components/page-heading";
import { getPendingPayments } from "@/lib/payments/queries";

export default async function AdminPaymentsPage() {
  let payments: Awaited<ReturnType<typeof getPendingPayments>> = []; let error = "";
  try { payments = await getPendingPayments(); } catch (e) { error = e instanceof Error ? e.message : "No se pudo abrir la bandeja."; }
  return <><PageHeading eyebrow="Administración" title="Revisión de pagos" description="La extracción automática orienta la revisión; la acreditación siempre requiere una decisión administrativa." />
    {error && <div className="mb-5 rounded-lg border border-amber-400/20 bg-amber-400/[0.06] p-5 text-sm text-amber-200">{error}</div>}
    <div className="space-y-4">{payments.map(p=><article key={p.id} className="grid gap-5 rounded-lg border border-white/[0.08] bg-white/[0.03] p-5 lg:grid-cols-[1fr_260px]"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-violet-500/15 px-2 py-1 text-xs text-violet-200">{p.package_id}</span><span className="text-xs text-slate-500">{p.status}</span></div><dl className="mt-5 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Esperado</dt><dd>{Number(p.expected_amount_bs).toLocaleString("es-VE")} Bs</dd></div><div><dt className="text-slate-500">Extraído</dt><dd>{p.extracted_amount_bs ? `${Number(p.extracted_amount_bs).toLocaleString("es-VE")} Bs` : "No detectado"}</dd></div><div><dt className="text-slate-500">Referencia</dt><dd>{p.extracted_reference || "No detectada"}</dd></div><div><dt className="text-slate-500">Créditos</dt><dd>{Number(p.credits).toLocaleString("es-VE")}</dd></div></dl><a href={p.receiptUrl} target="_blank" rel="noreferrer" className="mt-5 inline-flex text-sm text-violet-300 hover:underline">Abrir comprobante</a></div><form action={reviewPaymentForm} className="space-y-3"><input type="hidden" name="paymentId" value={p.id}/><textarea name="note" placeholder="Nota de revisión" className="min-h-24 w-full rounded-md border border-white/10 bg-black/30 p-3 text-sm outline-none focus:border-violet-400"/><div className="grid grid-cols-2 gap-2"><button name="decision" value="rejected" className="rounded-md border border-red-400/20 px-3 py-2 text-sm text-red-300">Rechazar</button><button name="decision" value="approved" className="rounded-md bg-violet-600 px-3 py-2 text-sm font-semibold">Aprobar</button></div></form></article>)}{!error && !payments.length && <div className="rounded-lg border border-dashed border-white/10 p-12 text-center text-sm text-slate-500">No hay comprobantes pendientes.</div>}</div>
  </>;
}
