# Supabase CLI Local Configuration

project_id = "bellas_artes"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://bellasartes-xi.vercel.app"
additional_redirect_urls = [
  "https://bellasartes-xi.vercel.app/**",
  "http://localhost:3000/**",
]
