"use client"

import Link from "next/link"
import { ArrowRight, SearchX } from "lucide-react"
import { useMemo, useState } from "react"
import { Badge } from "@/components/ui/badge"
import type { EditorialMetadata } from "@/lib/content/types"
import { cn } from "@/lib/utils"
import { CoverArt } from "./cover-art"

const filters = ["Todos", "Destacados", "Casos de estudio", "Novedades de Bellas Artes", "Guías de funciones", "Guías de video", "Guías de imagen"] as const
export function BlogIndex({ posts }: { posts: EditorialMetadata[] }) {
  const [filter, setFilter] = useState<(typeof filters)[number]>("Todos"); const featured = posts.find((post) => post.featured) ?? posts[0]; const visible = useMemo(() => posts.filter((post) => filter === "Todos" || (filter === "Destacados" ? post.featured : post.category === filter)), [filter, posts])
  return <div className="mx-auto max-w-7xl px-4 py-14 sm:px-7 sm:py-20"><section className="text-center"><Badge className="border border-violet-400/20 bg-violet-500/10 text-violet-200">Bellas Artes</Badge><h1 className="mt-6 bg-gradient-to-b from-white to-slate-500 bg-clip-text text-5xl font-semibold tracking-tight text-transparent sm:text-7xl">Historias para crear mejor.</h1><p className="mx-auto mt-5 max-w-2xl text-sm leading-6 text-slate-500">Novedades, guías y decisiones de producto para creadores de imagen, video y narrativa generativa.</p></section><div className="mt-10 flex gap-2 overflow-x-auto pb-2">{filters.map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={cn("min-w-fit rounded-full border px-4 py-2 text-xs transition", filter === item ? "border-violet-400 bg-violet-500/15 text-violet-200" : "border-white/[0.08] text-slate-500 hover:text-white")}>{item}</button>)}</div>{filter === "Todos" && featured && <Link href={`/blog/${featured.slug}`} className="group mt-12 grid overflow-hidden rounded-3xl border border-white/[0.08] bg-[#111114] md:grid-cols-2"><CoverArt tone={featured.cover} className="min-h-72"><Badge className="absolute top-5 left-5 bg-black/60 text-white">Destacado</Badge></CoverArt><div className="flex flex-col justify-center p-7 sm:p-10"><p className="text-xs text-violet-300">{featured.category} · {featured.publishedAt}</p><h2 className="mt-4 text-2xl font-semibold sm:text-3xl">{featured.title}</h2><p className="mt-4 text-sm leading-6 text-slate-500">{featured.excerpt}</p><span className="mt-7 flex items-center gap-2 text-sm text-white">Leer artículo <ArrowRight className="size-4 transition group-hover:translate-x-1" /></span></div></Link>}<section className="mt-12">{visible.length ? <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">{visible.map((post) => <Link key={post.slug} href={`/blog/${post.slug}`} className="group"><CoverArt tone={post.cover} className="aspect-video rounded-2xl border border-white/[0.08]" /><div className="mt-4 flex items-center gap-2 text-[10px] text-slate-600"><Badge className="bg-violet-500/10 text-violet-300">{post.category}</Badge><span>{post.publishedAt}</span></div><h2 className="mt-3 line-clamp-2 text-lg font-semibold text-slate-200 transition group-hover:text-violet-300">{post.title}</h2><p className="mt-2 line-clamp-3 text-xs leading-5 text-slate-600">{post.excerpt}</p></Link>)}</div> : <div className="flex min-h-72 flex-col items-center justify-center rounded-2xl border border-dashed border-white/10"><SearchX className="size-7 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No hay artículos en esta categoría.</p></div>}</section></div>
}
