"use client"

import { ImagePlus, LoaderCircle, Trash2 } from "lucide-react"
import { useEffect, useRef, useState } from "react"
import { Button } from "@/components/ui/button"
import type { BrandKitAsset } from "@/lib/brand-kits/contracts"

/* eslint-disable @next/next/no-img-element -- local previews and private signed URLs cannot use the optimizer. */

export function BrandLogoDropzone({ assets, onUpload, onRemove, busy }: { assets: BrandKitAsset[]; onUpload: (file: File) => Promise<void>; onRemove: (assetId: string) => Promise<void>; busy: boolean }) { const input = useRef<HTMLInputElement>(null); const [preview, setPreview] = useState<string | null>(null); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview) }, [preview]); async function select(file?: File) { if (!file) return; if (preview) URL.revokeObjectURL(preview); const url = URL.createObjectURL(file); setPreview(url); await onUpload(file); URL.revokeObjectURL(url); setPreview(null); if (input.current) input.current.value = "" } return <div><button type="button" onClick={() => input.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void select(event.dataTransfer.files[0]) }} className="flex min-h-40 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-white/20 bg-white/[0.035] p-8 text-center transition hover:bg-white/[0.06]"><input ref={input} type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" onChange={(event) => void select(event.target.files?.[0])} /><ImagePlus className="size-7 text-violet-300" /><p className="mt-3 text-sm text-slate-300">Arrastra o selecciona un logo</p><p className="mt-1 text-[10px] text-slate-600">PNG, JPG, WEBP o SVG · máximo 20 MB</p></button>{preview && <div className="mt-4 flex items-center gap-3 rounded-xl border border-violet-400/20 bg-violet-500/[0.06] p-3"><img src={preview} alt="Preview local" className="size-12 rounded-lg object-contain" /><LoaderCircle className="ml-auto size-4 animate-spin text-violet-300" /><span className="text-xs text-slate-400">Subiendo…</span></div>}<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{assets.map((asset) => <div key={asset.assetId} className="group relative aspect-square overflow-hidden rounded-xl border border-white/[0.08] bg-black"><>{asset.signedUrl ? <img src={asset.signedUrl} alt={asset.name} className="size-full object-contain p-3" /> : <span className="absolute inset-0 flex items-center justify-center text-[10px] text-slate-600">No disponible</span>}</><Button type="button" variant="destructive" size="icon-sm" disabled={busy} onClick={() => void onRemove(asset.assetId)} className="absolute top-2 right-2 opacity-0 group-hover:opacity-100"><Trash2 /></Button></div>)}</div></div> }
