export type ComfyTemplateCategory = "image" | "video" | "character" | "postprocess";
export type ComfyTemplateReadiness =
  | "mapping_required"
  | "custom_nodes_required"
  | "weights_missing"
  | "research_only";

export interface ComfyTemplateCatalogEntry {
  id: string;
  title: string;
  description: string;
  category: ComfyTemplateCategory;
  sourceRepo: string;
  sourceRepoUrl: string;
  sourceCommit: string;
  sourcePath: string;
  sourceFileUrl: string;
  starsSnapshot: number;
  starsObservedAt: "2026-08-14";
  license: "MIT" | "Apache-2.0";
  localPath: string;
  sha256: string;
  downloadFilename: string;
  modelIds: readonly string[];
  importReady: true;
  readiness: ComfyTemplateReadiness;
  requirements: readonly string[];
  compatibilityNote: string;
  adminOnly: true;
}

const COMFY_ORG = {
  sourceRepo: "Comfy-Org/workflow_templates",
  sourceRepoUrl: "https://github.com/Comfy-Org/workflow_templates",
  sourceCommit: "d9e66019b85da231b7c936ad9cb7ff08cec16557",
  starsSnapshot: 790,
  starsObservedAt: "2026-08-14",
  license: "MIT",
} as const;

const KIJAI_WAN = {
  sourceRepo: "kijai/ComfyUI-WanVideoWrapper",
  sourceRepoUrl: "https://github.com/kijai/ComfyUI-WanVideoWrapper",
  sourceCommit: "088128b224242e110d3906c6750e9a3a348a659b",
  starsSnapshot: 6665,
  starsObservedAt: "2026-08-14",
  license: "Apache-2.0",
} as const;

const CUBIQ = {
  sourceRepo: "cubiq/ComfyUI_Workflows",
  sourceRepoUrl: "https://github.com/cubiq/ComfyUI_Workflows",
  sourceCommit: "038cb775f2e8eb54bdbc99a8b9720177c7f8a336",
  starsSnapshot: 847,
  starsObservedAt: "2026-08-14",
  license: "Apache-2.0",
} as const;

export const COMFY_TEMPLATE_CATALOG = [
  {
    id: "flux-schnell-full-t2i",
    title: "FLUX.1 Schnell · Text to Image completo",
    description: "Workflow oficial con UNET, doble encoder, VAE y sampler de cuatro pasos.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/flux_schnell_full_text_to_image.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/flux_schnell_full_text_to_image.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/flux_schnell_full_text_to_image.json",
    sha256: "e17b1216c6f0edaf7c3bafa31ffe43b305f35246d8c33a93c363b5ee9adb4898",
    downloadFilename: "bellas-artes-flux-schnell-full-t2i.json",
    modelIds: ["flux-schnell"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["ComfyUI actualizado", "Mapear los encoders Diffusers a clip_l/t5xxl compatibles con ComfyUI"],
    compatibilityNote: "El transformer y el VAE están en el vault; los encoders requieren empaquetado o alias de archivos dentro del endpoint.",
    adminOnly: true,
  },
  {
    id: "flux-dev-full-t2i",
    title: "FLUX.1 Dev · Text to Image completo",
    description: "Workflow oficial de mayor calidad para evaluación comparativa privada.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/flux_dev_full_text_to_image.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/flux_dev_full_text_to_image.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/flux_dev_full_text_to_image.json",
    sha256: "235c3fb8eb7aa56fb6b56d578868912152e39574967758a8424cb60436beb3fc",
    downloadFilename: "bellas-artes-flux-dev-full-t2i.json",
    modelIds: ["flux-dev"],
    importReady: true,
    readiness: "research_only",
    requirements: ["ComfyUI actualizado", "Pesos/encoders convertidos a layout ComfyUI", "Uso administrativo no comercial"],
    compatibilityNote: "Los pesos están instalados, pero la licencia local limita este workflow a investigación privada.",
    adminOnly: true,
  },
  {
    id: "sd35-simple",
    title: "Stable Diffusion 3.5 · Simple",
    description: "Grafo oficial compacto para aprender y adaptar el flujo SD3.5.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/sd3.5_simple_example.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/sd3.5_simple_example.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/sd3.5_simple_example.json",
    sha256: "22636f8ea8d35f41ecf92917112e14376bc30ae2c01de0b9553493cf2c176619",
    downloadFilename: "bellas-artes-sd35-simple.json",
    modelIds: ["sd35-medium"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["Cambiar el checkpoint Large del ejemplo por sd3.5_medium.safetensors", "Validar CLIP/VAE del paquete Medium"],
    compatibilityNote: "La plantilla original usa SD3.5 Large FP8; Bellas Artes tiene Medium y debe mapear el loader antes del smoke.",
    adminOnly: true,
  },
  {
    id: "flux2-klein-4b-t2i",
    title: "FLUX.2 Klein 4B · Text to Image",
    description: "Plantilla oficial con subgraph para generación rápida y edición posterior.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/image_flux2_klein_text_to_image.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/image_flux2_klein_text_to_image.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/image_flux2_klein_text_to_image.json",
    sha256: "f5b2e75448e1ef44ab3d08da00900000f0258f8f963934370c6a1c329d1328c2",
    downloadFilename: "bellas-artes-flux2-klein-4b-t2i.json",
    modelIds: ["flux2-klein-4b"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["ComfyUI con soporte de subgraphs", "Mapear el paquete instalado al layout diffusion_models/text_encoders/vae"],
    compatibilityNote: "El modelo está íntegro en el vault, pero la plantilla espera el repack split de Comfy-Org.",
    adminOnly: true,
  },
  {
    id: "qwen-image-t2i",
    title: "Qwen-Image · Text to Image",
    description: "Workflow oficial orientado a tipografía, composición y prompts complejos.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/image_qwen_image.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/image_qwen_image.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/image_qwen_image.json",
    sha256: "0f1dfed53e4d37d47a3c5fe93516c342b3b5b5961b8fbc169c2fffd53ae59349",
    downloadFilename: "bellas-artes-qwen-image-t2i.json",
    modelIds: ["qwen-image"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["GPU de alta VRAM", "Repack FP8 o adaptación del paquete oficial instalado", "LoRA Lightning sólo si se autoriza aparte"],
    compatibilityNote: "El vault contiene Qwen-Image oficial; la plantilla selecciona un repack FP8 y una LoRA que no deben descargarse automáticamente.",
    adminOnly: true,
  },
  {
    id: "z-image-t2i",
    title: "Z-Image · Text to Image",
    description: "Plantilla oficial base para retrato y generación eficiente.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/image_z_image.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/image_z_image.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/image_z_image.json",
    sha256: "f7b3ceb43a3688e17cc5bce67d1beafe833a674b4e4a257c626a6243b3ebedc2",
    downloadFilename: "bellas-artes-z-image-t2i.json",
    modelIds: ["z-image"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["ComfyUI con soporte Z-Image", "Mapear el paquete instalado a diffusion_models/text_encoders/vae"],
    compatibilityNote: "Los pesos base están instalados; la plantilla espera archivos split con nombres de Comfy-Org.",
    adminOnly: true,
  },
  {
    id: "wan22-5b-ti2v",
    title: "Wan 2.2 5B · TI2V",
    description: "Workflow oficial nativo para texto o imagen a video con el modelo TI2V-5B.",
    category: "video",
    ...COMFY_ORG,
    sourcePath: "templates/video_wan2_2_5B_ti2v.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/video_wan2_2_5B_ti2v.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/video_wan2_2_5B_ti2v.json",
    sha256: "50390798a133757075d750ab78b26274e3bf3e4a09f46aaa2f08d9559e62750b",
    downloadFilename: "bellas-artes-wan22-5b-ti2v.json",
    modelIds: ["wan22-ti2v-5b"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["ComfyUI actualizado", "Empaquetar el modelo instalado como diffusion model/VAE/text encoder de ComfyUI", "GPU de 24 GB"],
    compatibilityNote: "El repositorio y los pesos originales están instalados; falta crear el layout single-file que espera el workflow.",
    adminOnly: true,
  },
  {
    id: "hunyuan15-720p-t2v",
    title: "HunyuanVideo 1.5 · 720p T2V",
    description: "Workflow oficial con generación 720p y superresolución latente.",
    category: "video",
    ...COMFY_ORG,
    sourcePath: "templates/video_hunyuan_video_1.5_720p_t2v.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/video_hunyuan_video_1.5_720p_t2v.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/video_hunyuan_video_1.5_720p_t2v.json",
    sha256: "b52ab35cd7f5253288d32ca2d18329607a0e5fb265886e234bae7b75deff8cfe",
    downloadFilename: "bellas-artes-hunyuan15-720p-t2v.json",
    modelIds: ["hunyuan-video-15-83b"],
    importReady: true,
    readiness: "weights_missing",
    requirements: ["Pesos ComfyUI 720p T2V", "Modelo de superresolución 1080p", "GPU y presupuesto de video"],
    compatibilityNote: "El vault secundario conserva la variante 480p T2V destilada; los pesos 720p/SR del ejemplo no están instalados.",
    adminOnly: true,
  },
  {
    id: "hunyuan15-720p-i2v",
    title: "HunyuanVideo 1.5 · 720p I2V",
    description: "Workflow oficial de imagen a video con SigLIP y superresolución.",
    category: "video",
    ...COMFY_ORG,
    sourcePath: "templates/video_hunyuan_video_1.5_720p_i2v.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/video_hunyuan_video_1.5_720p_i2v.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/video_hunyuan_video_1.5_720p_i2v.json",
    sha256: "4f6ab488b60f7b70f6501217c1ed697a366f29c3c36755e87ef76f6023676015",
    downloadFilename: "bellas-artes-hunyuan15-720p-i2v.json",
    modelIds: ["hunyuan-video-15-83b"],
    importReady: true,
    readiness: "weights_missing",
    requirements: ["Pesos 720p I2V", "SigLIP vision", "Modelo de superresolución", "GPU y presupuesto de video"],
    compatibilityNote: "Se incluye para preparar el benchmark grande, pero sus pesos I2V/SR no forman parte del vault actual.",
    adminOnly: true,
  },
  {
    id: "real-esrgan-video-upscale",
    title: "Real-ESRGAN · GAN Video Upscaler",
    description: "Workflow oficial rápido para escalar video sin difusión adicional.",
    category: "postprocess",
    ...COMFY_ORG,
    sourcePath: "templates/utility-gan_upscaler.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/utility-gan_upscaler.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/utility-gan_upscaler.json",
    sha256: "83847146f0cb0e8e8b8c6012d3e635e29ee2706697e58331a3fa6db97f645980",
    downloadFilename: "bellas-artes-real-esrgan-video-upscale.json",
    modelIds: ["real-esrgan"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["Seleccionar RealESRGAN_x4plus.pth en UpscaleModelLoader", "ComfyUI con nodos de video core"],
    compatibilityNote: "El peso .pth oficial está instalado; la plantilla upstream propone el repack .safetensors y debe cambiarse en el selector.",
    adminOnly: true,
  },
  {
    id: "wan22-5b-controlnet-depth",
    title: "Wan 2.2 5B · ControlNet Depth",
    description: "Workflow avanzado del wrapper de Kijai para video guiado por profundidad.",
    category: "video",
    ...KIJAI_WAN,
    sourcePath: "example_workflows/wanvideo_2_2_5B_T2V_controlnet_example.json",
    sourceFileUrl: `${KIJAI_WAN.sourceRepoUrl}/blob/${KIJAI_WAN.sourceCommit}/example_workflows/wanvideo_2_2_5B_T2V_controlnet_example.json`,
    localPath: "workflows/templates/vendor/kijai-wan/example_workflows/wanvideo_2_2_5B_T2V_controlnet_example.json",
    sha256: "199582cdc2a2d7fbaaf0a99cffecf0f0c79dafa11f0d9b7c0f5711ab5edee948",
    downloadFilename: "bellas-artes-wan22-5b-controlnet-depth.json",
    modelIds: ["wan22-ti2v-5b", "controlnet-dwpose"],
    importReady: true,
    readiness: "custom_nodes_required",
    requirements: ["ComfyUI-WanVideoWrapper", "VideoHelperSuite/KJNodes", "ControlNet Wan 2.2 Depth no instalado"],
    compatibilityNote: "Es una referencia avanzada; no se ejecuta con el vault actual hasta instalar el ControlNet específico y fijar custom nodes.",
    adminOnly: true,
  },
  {
    id: "sdxl-checkpoint-study",
    title: "SDXL Base + Refiner · estudio de checkpoints",
    description: "Workflow didáctico para comparar checkpoints SDXL instalados y un refiner opcional.",
    category: "image",
    ...CUBIQ,
    sourcePath: "basic/SDXL_simple.json",
    sourceFileUrl: `${CUBIQ.sourceRepoUrl}/blob/${CUBIQ.sourceCommit}/basic/SDXL_simple.json`,
    localPath: "workflows/templates/vendor/cubiq/basic/SDXL_simple.json",
    sha256: "d3db2dcc2a8773f1e0ac3e18942b466f37b20cabf47760d7dd9fafc75c5cccab",
    downloadFilename: "bellas-artes-sdxl-checkpoint-study.json",
    modelIds: ["juggernaut-xl", "dynavision-xl", "wai-ani-ponyxl"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["Cambiar el checkpoint base por uno de los SDXL instalados", "Refiner SDXL opcional no instalado", "Respetar la política privada de cada checkpoint"],
    compatibilityNote: "Juggernaut, DynaVision y WAI-ANI caben en este grafo, pero continúan sólo para investigación hasta cerrar permisos y moderación.",
    adminOnly: true,
  },
  {
    id: "dwpose-guided-composition",
    title: "DWPose · Guided Composition",
    description: "Workflow didáctico de Cubiq para controlar pose con DWPose y ControlNet.",
    category: "character",
    ...CUBIQ,
    sourcePath: "guided_composition/pose.json",
    sourceFileUrl: `${CUBIQ.sourceRepoUrl}/blob/${CUBIQ.sourceCommit}/guided_composition/pose.json`,
    localPath: "workflows/templates/vendor/cubiq/guided_composition/pose.json",
    sha256: "f3f507279874bf772461122066828993fed1350f5a1cdbba9b9e886fbdcafd76",
    downloadFilename: "bellas-artes-dwpose-guided-composition.json",
    modelIds: ["controlnet-dwpose"],
    importReady: true,
    readiness: "custom_nodes_required",
    requirements: ["ComfyUI ControlNet Aux para DWPreprocessor", "Seleccionar un checkpoint SD1.5 compatible", "Mapear el ControlNet OpenPose instalado"],
    compatibilityNote: "DWPose y el ControlNet SD1.5 están instalados; falta fijar el custom node y un modelo base compatible.",
    adminOnly: true,
  },
  {
    id: "real-esrgan-image-upscale-study",
    title: "Upscale by Model · estudio comparativo",
    description: "Workflow didáctico para comparar upscale por modelo y refinado latente.",
    category: "postprocess",
    ...CUBIQ,
    sourcePath: "upscale/upscale_by_model.json",
    sourceFileUrl: `${CUBIQ.sourceRepoUrl}/blob/${CUBIQ.sourceCommit}/upscale/upscale_by_model.json`,
    localPath: "workflows/templates/vendor/cubiq/upscale/upscale_by_model.json",
    sha256: "3aa8617f5dd5a9b521a9f549882807216d941edbd2f3ee0bfc7079be3db58f13",
    downloadFilename: "bellas-artes-real-esrgan-image-upscale-study.json",
    modelIds: ["real-esrgan"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["Elegir RealESRGAN_x4plus.pth", "Sustituir el checkpoint SD1.5 del ejemplo si se usa la etapa de refinado"],
    compatibilityNote: "La rama de upscale puede usar el peso instalado; la rama de refinado necesita un checkpoint base compatible.",
    adminOnly: true,
  },
  {
    id: "flux-schnell-minimal",
    title: "FLUX.1 Schnell · flujo mínimo",
    description: "La plantilla oficial compacta para validar rápidamente el checkpoint Schnell.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/flux_schnell.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/flux_schnell.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/flux_schnell.json",
    sha256: "912fe178607a2c0e1ff12688703d22b34866949c9669ecc2739d19971e916b96",
    downloadFilename: "bellas-artes-flux-schnell-minimal.json",
    modelIds: ["flux-schnell"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["ComfyUI actualizado", "Checkpoint flux1-schnell-fp8.safetensors o alias del paquete Diffusers"],
    compatibilityNote: "Es el candidato más pequeño para convertir el paquete Diffusers de Schnell y hacer el primer smoke visual.",
    adminOnly: true,
  },
  {
    id: "sdxl-simple-official",
    title: "SDXL · simple oficial",
    description: "Flujo oficial directo para comparar los checkpoints SDXL del vault.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/sdxl_simple_example.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/sdxl_simple_example.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/sdxl_simple_example.json",
    sha256: "7f3825deea7a3fc494dbbe8838d92336e7bb44d9faf179149b73193305b68f24",
    downloadFilename: "bellas-artes-sdxl-simple-official.json",
    modelIds: ["juggernaut-xl", "dynavision-xl", "wai-ani-ponyxl"],
    importReady: true,
    readiness: "mapping_required",
    requirements: ["Elegir un checkpoint SDXL instalado", "Mapear el nombre del checkpoint al loader"],
    compatibilityNote: "A diferencia del estudio Base + Refiner, esta versión es el smoke mínimo sin refiner adicional.",
    adminOnly: true,
  },
  {
    id: "flux2-klein-4b-image-edit",
    title: "FLUX.2 Klein 4B · edición de imagen",
    description: "Template oficial de edición por imagen de referencia con subgraph Klein.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/image_flux2_klein_image_edit_4b_base.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/image_flux2_klein_image_edit_4b_base.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/image_flux2_klein_image_edit_4b_base.json",
    sha256: "346cd9a63bfe34a5a9207f50c34a87feaf4e70806d13c9d2738fd521133670d0",
    downloadFilename: "bellas-artes-flux2-klein-4b-image-edit.json",
    modelIds: ["flux2-klein-4b"],
    importReady: true,
    readiness: "custom_nodes_required",
    requirements: ["ComfyUI con soporte de subgraphs", "Checkpoint y text encoder Klein en layout ComfyUI", "Imagen de entrada"],
    compatibilityNote: "El JSON es una plantilla oficial de subgraph; el vault tiene el paquete base, pero falta validar su repack y blueprint local.",
    adminOnly: true,
  },
  {
    id: "qwen-image-edit-official",
    title: "Qwen-Image · edición oficial",
    description: "Template oficial para editar una imagen manteniendo composición y contexto.",
    category: "image",
    ...COMFY_ORG,
    sourcePath: "templates/image_qwen_image_edit.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/image_qwen_image_edit.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/image_qwen_image_edit.json",
    sha256: "2c8a46d0f89dd0956d4422a92aab15363fbdec51a7cc4d1350f4a9d3ef268d48",
    downloadFilename: "bellas-artes-qwen-image-edit-official.json",
    modelIds: ["qwen-image"],
    importReady: true,
    readiness: "custom_nodes_required",
    requirements: ["ComfyUI con subgraph Qwen Image Edit", "Modelo Qwen-Image Edit compatible", "Imagen de entrada"],
    compatibilityNote: "Se conserva para preparar edición; el paquete Qwen-Image instalado requiere validar si incluye la variante Edit esperada.",
    adminOnly: true,
  },
  {
    id: "wan22-5b-fun-control",
    title: "Wan 2.2 5B · Fun Control",
    description: "Template oficial de video guiado por una secuencia de control Canny.",
    category: "video",
    ...COMFY_ORG,
    sourcePath: "templates/video_wan2_2_5B_fun_control.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/video_wan2_2_5B_fun_control.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/video_wan2_2_5B_fun_control.json",
    sha256: "2e80a254d3fb263f02d1a74e6abb0676d4dbb6aaf813575bf75ff4bda7bbb40d",
    downloadFilename: "bellas-artes-wan22-5b-fun-control.json",
    modelIds: ["wan22-ti2v-5b"],
    importReady: true,
    readiness: "weights_missing",
    requirements: ["Pesos Wan 2.2 Fun Control 5B", "Video de control Canny", "GPU de video y presupuesto controlado"],
    compatibilityNote: "El modelo TI2V-5B está instalado, pero los pesos específicos Fun Control no forman parte del vault y no se descargarán automáticamente.",
    adminOnly: true,
  },
  {
    id: "film-frame-interpolation",
    title: "FILM · interpolación de frames",
    description: "Template oficial para interpolar frames de un video con FILM.",
    category: "postprocess",
    ...COMFY_ORG,
    sourcePath: "templates/utility-frame_interpolation-film.json",
    sourceFileUrl: `${COMFY_ORG.sourceRepoUrl}/blob/${COMFY_ORG.sourceCommit}/templates/utility-frame_interpolation-film.json`,
    localPath: "workflows/templates/vendor/comfy-org/templates/utility-frame_interpolation-film.json",
    sha256: "a7745708eff6cc17fdb9bcfaa681d0e413fdb3019d09e5f21723c33af5683572",
    downloadFilename: "bellas-artes-film-frame-interpolation.json",
    modelIds: ["practical-rife"],
    importReady: true,
    readiness: "custom_nodes_required",
    requirements: ["ComfyUI-Frame-Interpolation", "ComfyUI-VideoHelperSuite", "Video de entrada"],
    compatibilityNote: "El vault ya tiene RIFE como auxiliar, pero esta plantilla requiere el custom node FILM y no modifica la cola pública.",
    adminOnly: true,
  },
] as const satisfies readonly ComfyTemplateCatalogEntry[];

export interface ReviewedComfyRepository {
  repository: string;
  url: string;
  starsSnapshot: number;
  workflowCount: number;
  license: string;
  imported: false;
  reason: string;
}

export const REVIEWED_COMFY_REPOSITORIES = [
  {
    repository: "cubiq/ComfyUI_IPAdapter_plus",
    url: "https://github.com/cubiq/ComfyUI_IPAdapter_plus",
    starsSnapshot: 6096,
    workflowCount: 21,
    license: "GPL-3.0",
    imported: false,
    reason: "Requiere pesos IPAdapter no instalados y varias rutas FaceID dependen de InsightFace; se excluye del catálogo utilizable.",
  },
  {
    repository: "kijai/ComfyUI-HunyuanVideoWrapper",
    url: "https://github.com/kijai/ComfyUI-HunyuanVideoWrapper",
    starsSnapshot: 2595,
    workflowCount: 13,
    license: "No declarada por GitHub",
    imported: false,
    reason: "No se copian workflows sin licencia explícita; Bellas Artes usa las plantillas oficiales MIT de HunyuanVideo 1.5.",
  },
  {
    repository: "XLabs-AI/x-flux-comfyui",
    url: "https://github.com/XLabs-AI/x-flux-comfyui",
    starsSnapshot: 1703,
    workflowCount: 9,
    license: "Apache-2.0; pesos FLUX Dev no comerciales",
    imported: false,
    reason: "Sus workflows requieren custom nodes y pesos ControlNet/IPAdapter distintos a los instalados; se conserva como referencia de investigación.",
  },
  {
    repository: "ZHO-ZHO-ZHO/ComfyUI-Workflows-ZHO",
    url: "https://github.com/ZHO-ZHO-ZHO/ComfyUI-Workflows-ZHO",
    starsSnapshot: 7735,
    workflowCount: 17,
    license: "GPL-3.0",
    imported: false,
    reason: "Es una colección grande y popular, pero GPL-3.0 no encaja con la redistribución de templates dentro del producto comercial.",
  },
  {
    repository: "comfyanonymous/ComfyUI_examples",
    url: "https://github.com/comfyanonymous/ComfyUI_examples",
    starsSnapshot: 4463,
    workflowCount: 21,
    license: "Sin licencia detectada por GitHub",
    imported: false,
    reason: "Referencia oficial muy valiosa, con ejemplos de Wan, Hunyuan, LTXV y Cosmos; se enlaza hasta que exista una licencia redistribuible explícita.",
  },
  {
    repository: "wyrde/wyrde-comfyui-workflows",
    url: "https://github.com/wyrde/wyrde-comfyui-workflows",
    starsSnapshot: 1272,
    workflowCount: 44,
    license: "MIT",
    imported: false,
    reason: "Colección MIT amplia, pero los ejemplos revisados apuntan a checkpoints SD1.5, LoRAs y upscalers que no están en el vault actual.",
  },
  {
    repository: "SeargeDP/SeargeSDXL",
    url: "https://github.com/SeargeDP/SeargeSDXL",
    starsSnapshot: 874,
    workflowCount: 14,
    license: "MIT",
    imported: false,
    reason: "Incluye workflows SDXL completos, pero todos dependen del custom node SeargeSDXL; no se instala una extensión de terceros durante esta revisión.",
  },
  {
    repository: "masslevel/ComfyUI-Workflows",
    url: "https://github.com/masslevel/ComfyUI-Workflows",
    starsSnapshot: 24,
    workflowCount: 4,
    license: "CC0-1.0",
    imported: false,
    reason: "Tiene una alternativa FLUX Schnell y ejemplos Wan, pero requiere varios custom nodes y usa Wan 2.1 14B, que no está instalado.",
  },
  {
    repository: "Comfy-Org/example_workflows",
    url: "https://github.com/Comfy-Org/example_workflows",
    starsSnapshot: 25,
    workflowCount: 20,
    license: "Sin licencia detectada por GitHub",
    imported: false,
    reason: "Contiene ejemplos actuales, pero mezcla API nodes de proveedores externos y no declara una licencia redistribuible.",
  },
] as const satisfies readonly ReviewedComfyRepository[];

export function listComfyTemplateCatalog() {
  return [...COMFY_TEMPLATE_CATALOG];
}

export function getComfyTemplateCatalogEntry(id: string) {
  return COMFY_TEMPLATE_CATALOG.find((entry) => entry.id === id) ?? null;
}

export function summarizeComfyTemplateCatalog() {
  return {
    total: COMFY_TEMPLATE_CATALOG.length,
    repositories: new Set(COMFY_TEMPLATE_CATALOG.map((entry) => entry.sourceRepo)).size,
    image: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.category === "image").length,
    video: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.category === "video").length,
    character: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.category === "character").length,
    postprocess: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.category === "postprocess").length,
    customNodes: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.readiness === "custom_nodes_required").length,
    weightsMissing: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.readiness === "weights_missing").length,
    researchOnly: COMFY_TEMPLATE_CATALOG.filter((entry) => entry.readiness === "research_only").length,
  };
}
